%% SETTINGS

clc;        % Очистить командное окно
clear all;  % Очистить все переменные
close all;  % Закрыть все окна с графиками

addpath('my_functions/');
addpath('my_functions_2/');

% Bits = 0;
% rows = 0;
% cols = 0;

[Bits, rows, cols] =  ImageToBits("test_picture.jpg",...
                                  "gray", ...
                                  "on", ...
                                  "on");



Image = BitsToImage(Bits,  ...
                    rows, ...
                    cols, ...
                    "gray", ...
                    "on", ...
                    "on");
